version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GROK_API_KEY=${GROK_API_KEY}
    volumes:
      - .:/app
    networks:
      - github-agent-network

  frontend:
    build:
      context: ./github-summary-app
      dockerfile: Dockerfile.frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000
    networks:
      - github-agent-network

networks:
  github-agent-network:
    driver: bridge